name: Daily Reminder

on:
  schedule:
    - cron: '45 10 * * *'  # 台灣時間 18:45（UTC+8 → UTC 10:45）
  workflow_dispatch:  # 手動觸發用

jobs:
  run-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run reminder script
        run: python reminder.py
