name: Reminder Bot Scheduler

on:
  push:
    branches:
      - master  # 只在 master 分支上推送時觸發
  schedule:
    - cron: '55 10 * * *'  # 台灣時間 18:45 (UTC+8 -> UTC 10:45)
  workflow_dispatch:  # 也允許手動觸發
jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 這會檢出 master 分支的程式碼

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run reminder script
      run: |
        python reminder.py  # 執行 reminder.py 這個檔案
