name: Reminder Bot Scheduler

on:
  schedule:
    - cron: '30 03 * * *'  # UTC 03:30 → 台灣時間 11:30
  workflow_dispatch:  # 也允許手動觸發
jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # 這會檢出 master 分支的程式碼

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run reminder script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        python reminder.py  # 執行 reminder.py 這個檔案
