name: Reminder Bot Scheduler

on:
  schedule:
    - cron: '0 14 * * *'  # 每天 UTC 14:00 = 台灣 22:00
  workflow_dispatch:

jobs:
  reminder:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run reminder script
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
      run: |
        echo "GitHub Action Triggered at $(date)"
        python reminder.py
